ENT-3531: Set proper permissions for php binary in hub package
This was world writeable causing security alerts and preventing cf-agent
from executing the command as desired.

   error: SECURITY ALERT: promised executable
'/var/cfengine/httpd/php/bin/php' is world writable!
   error: SECURITY ALERT: CFEngine will not execute this - requires
human inspection