Fixed fatal error: sys/random.h: No such file or directory
When building git dependency on redhat 7 with git v2.50 we get a
compilation error due to the include of a missing file.

```
15:05:27 + make CURL_LDFLAGS=-lcurl
15:05:28 GIT_VERSION=2.50.0
15:05:28     * new build flags
15:05:28     CC daemon.o
15:05:28 In file included from git-compat-util.h:26:0,
15:05:28                  from daemon.c:3:
15:05:28 compat/posix.h:159:24: fatal error: sys/random.h: No such file or directory
15:05:28  #include <sys/random.h>
15:05:28                         ^
15:05:28 compilation terminated.
```

Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 16fc9aa1b339211d63f5988c6366319649a38bd6)