rsync: patch syscall.c to define SYS_openat2 when missing
Some kernel-headers packages ship <linux/openat2.h> but do not export
SYS_openat2 from <asm/unistd.h>, causing rsync 3.4.3's syscall.c to
fail to compile:

    syscall.c: In function 'secure_relative_open_linux':
    syscall.c:1723:19: error: 'SYS_openat2' undeclared (first use in this function); did you mean 'SYS_openat'?
     1723 |   dirfd = syscall(SYS_openat2, AT_FDCWD, basedir, &bhow, sizeof bhow);
          |                   ^~~~~~~~~~~
          |                   SYS_openat

Apply a source patch that adds a fallback #define SYS_openat2 437
(the syscall number is the same on all Linux architectures).

Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>