Fixed implicit declaration of fopen()
After upgrading to curl 8.16.0 we got

```
altsvc.c: In function 'altsvc_load':
altsvc.c:230:8: error: implicit declaration of function 'fopen' [-Werror=implicit-function-declaration]
   fp = fopen(file, FOPEN_READTEXT);
        ^~~~~
```

on AIX 7.1. The header stdio.h is probably included indirectly on all
other platforms.

Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 8a52b02590f24b2b5ada02f334fa497f2a68833f)