Fixed undefined reference to _set_printf_count_output on MinGW
Ticket: ENT-13259
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 367edcd83e8dac266131d64bc4fb826cf59f6388)