Fixed curl failing to build for Windows
Fixes following issue on Windows build
```
15:44:06 url.c: In function 'zonefrom_url':
15:44:06 url.c:1802:18: error: implicit declaration of function 'if_nametoindex' [-Werror=implicit-function-declaration]
15:44:06        scopeidx = if_nametoindex(zoneid);
15:44:06                   ^
```

Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 4512cfe3e72f8915528c20cd35aaaf1816b3a402)