Only run 'chkconfig --del' on uninstall if we shipped /etc/init.d/cfengine3
Otherwise it fails and the whole scriptlet fails like this:

  error: %preun(cfengine-nova-3.24.0a.c3a2325e3-33984.el9.x86_64) scriptlet failed, exit status 1
  error: cfengine-nova-3.24.0a.c3a2325e3-33984.el9.x86_64: erase failed

keeping the package installed.

Ticket: ENT-11901
Changelog: None
(cherry picked from commit 58761bb7fde75fec8ecc76b732d09abc7d5af77d)