Fixed duplicate case value when compiling libxml2 on AIX
This is the error we got:
```
00:01:07 xmlIO.c: In function 'xmlIOErr':
00:01:07 xmlIO.c:502:9: error: duplicate case value
00:01:07          case ENOTEMPTY: code = XML_IO_ENOTEMPTY; break;
00:01:07          ^~~~
00:01:07 xmlIO.c:439:9: error: previously used here
00:01:07          case EEXIST: code = XML_IO_EEXIST; break;
00:01:07          ^~~~
```

It appears that the `ENOTEMPTY` & `EEXITS` are defined as the same
value. Defining `_LINUX_SOURCE_COMPAT` should give them unique values.

```C
/*
 * AIX returns EEXIST where 4.3BSD used ENOTEMPTY;
 * but, the standards insist on unique errno values for each errno.
 * A unique value is reserved for users that want to code case
 * statements for systems that return either EEXIST or ENOTEMPTY.
 */
```

Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 794e1fde6cc034d389d6eb6d8e2e6a109f1cd95e)