Upgrade to LMDB 0.9.19
Note in particular the addition of:
  AM_CPPFLAGS = -D_POSIX_PTHREAD_SEMANTICS

This gets rid of an error on Solaris:
  mdb.c: In function 'mdb_env_copythr':
  mdb.c:9046:6: error: too many arguments to function 'sigwait'
  /opt/csw/lib/gcc/sparc-sun-solaris2.9/4.6.3/include-fixed/signal.h:218:12: note: declared here
  gmake: *** [mdb.lo] Error 1

Most of the other changes are just regenerated autoconf files.

Changelog: Title
Signed-off-by: Kristian Amlie <kristian.amlie@cfengine.com>
(cherry picked from commit 6ef5dbb0398284480bf2d7ac522c92f86b41eec1)