Added assert on EINVAL in mdb_mutex_failed()
To debug issues related to the following log message:

error: Could not open database txn /var/cfengine/state/cf_lock.lmdb: Invalid argument

Ticket: CFE-3807
Changelog: title
(cherry picked from commit 43434600f675b352b1fcbd41ef3054df3270c397)