Fixed implicit declaration of GNU extension gettid
Fixes current compilation error (found on Ubuntu 24):

```
23:16:48 log.c:637:21: error: implicit declaration of function 'gettid'; did you mean 'getgid'? [-Wimplicit-function-declaration]
23:16:48   637 |         pid_t tid = gettid();
23:16:48       |                     ^~~~~~
23:16:48       |                     getgid
```

Ticket: ENT-13084
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>
(cherry picked from commit 505768771c655139e8d35e9553becbf478120ece)