create-empty-test: removed escape sequence from double quotes
After simplifying the create-empty-test script in
https://github.com/cfengine/buildscripts/pull/1815/files we no longer
need to escape the double quotes. Doing so causes the literal backslash
to be included causing the following error:

```
org.dom4j.DocumentException: Error on line 1 of document  : The value following "version" in the XML declaration must be a quoted string.
```

Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>